;;; ~/comp/ext/stumpwm/contrib/util/util.asd --- Util Sytem Definitions
(defsystem :util
  :depends-on (:std :swank :wm :dat :xlib :xlib/truetype :ppcre)
  :components ((:file "pkg")
               (:file "golden-ratio")
               (:file "beckon")
               (:file "clipboard")
               (:file "history")
               (:file "globalwindows")
               (:file "kbd-layouts")
               (:file "perwindowlayout")
               (:file "screenshot")
               (:file "spatial-groups")
               (:file "gaps")
               (:file "ttf-fonts")
               (:file "windowtags")
               (:file "urgentwindows")
               (:file "winner")))
